version: '3'
services: 
  nightswatch:
    image: iad2os/nightswatch
    volumes: 
      - ./config-simple.yaml:/app/config.yaml
    environment: 
      CONFIG_FILE: ./config.yaml
    ports:
      - 3000:3000
